import type { NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/layout'
import NewestPosts from '../components/posts'
import Session from '../components/auth/Session'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/src/public/favicon.ico" />
      </Head>

      <Layout>
        <div>
          <Session />
          <NewestPosts />
        </div>
      </Layout>
    </div>
  )
}

export default Home
